// constants/columns.ts

export const MASTER_COLUMNS_MAP: Record<string, string[]> = {
  ic: [
    "STT No",
    "STT Booked At",
    "Periode",
    "Jenis Kiriman",
    "Shipment ID",
    "Invoice Marketplace",
    "External ID",
    "Client Name",
    "Client Code",
    "Customer Branch Name",
    "Origin",
    "Forward Area Origin",
    "Destination",
    "Forward Area Destination",
    "Product",
    "Commodity Name",
    "Last Status",
    "Source",
    "Sub Source",
    "Mother Account",
    "Customer Code",
    "POD Date",
    "RTS/ RTSHQ Date",
    "Pcs",
    "Volume Weight",
    "Gross Weight",
    "Chargeable Weight",
    "Qty Samsung",
    "Publish Rate/Kg",
    "Publish Rate Cost/Kg",
    "Heavyweight Surcharge Rate",
    "Commodity Surcharge Rate",
    "Forward Rate Origin",
    "Forward Rate Destination",
    "COD Amount",
    "Value Of Goods",
    "Surcharge Rate",
    "Shipping Surcharge",
    "Woodpacking Fee",
    "Woodpacking Revenue",
    "Document Surcharge Rate",
    "Insurance Rate",
    "Total Amount Rate",
    "Total Amount Rate Original",
    "Total Vat",
    "COD Revenue",
    "VAT COD Revenue",
    "Total Cargo",
    "Booking Commission",
    "Insurance Commission",
    "Forward Booking Commission",
    "Booking Return",
    "Booking Return Revert",
    "Cargo Category",
    "Route Type",
    "First AWB Number",
    "Last AWB Number",
    "Lag Route",
    "Lag Moda",
    "Client Payment Method",
    "Invoice Number",
    "SO Number",
    "Delivered by",
    "Remarks",
    "Source Group",
    "Booking ID Additional",
    "Client Category",
    "PublishRateFeeFixed",
    "Month", // Tambahan untuk filter internal
  ],
  ls: [
    "STT No",
    "STT Booked At",
    "STT Booked By",
    "Product",
    "Last Status",
    "STT Updated At",
    "STT Updated Actor Name",
    "STT Updated Actor Role",
    "Source",
  ],
  dt: [
    "STT No",
    "Booked At",
    "Last Status",
    "Ori gin",
    "Dest.",
    "Forward Area Destination",
    "Product",
    "Starting Status",
    "End Status",
    "Starting Point",
    "End Point",
    "Updated By Partner",
    "Tier",
    "% Deliv. Fee",
    "SDN Remarks",
    "Adjust Remarks",
    "Del Type",
    "STT Type",
    "Area",
    "Dex Code",
    "Remarks",
    "Keterangan",
    "Publish Rate Cost",
    "Chargeable Weight",
    "Delivery Fee",
    "Bonus/Pinalti",
    "Total Bonus / Pinalti",
  ],
  mt: [
    "Cargo ID",
    "Cargo No",
    "Cargo Type",
    "Cargo Vehicle No",
    "Cargo Origin City Code",
    "Cargo Origin AirportCode",
    "Cargo Destination Airport Code",
    "Cargo Destination City Code",
    "Cargo Remark",
    "Cargo Created At",
    "Cargo Created By",
    "Cargo Created Name",
    "Cargo Updated At",
    "Cargo Updated By",
    "Cargo Updated Name",
    "Cargo Partner Name",
    "Cargo Partner Code",
    "Cargo Partner Type",
    "Cargo Partner ID",
    "Cargo Total Stt",
    "Cargo Total Stt Piece",
    "Cargo Total Gross Weight",
    "Cargo Total Volume Weight",
    "Cargo Total Custom Gross Weight",
    "Cargo Total Custom Volume Weight",
    "Cargo Total Estimate Gross Weight",
    "Cargo Total Estimate Volume Weight",
    "Cargo Cargo Product Type Code",
    "Cargo Commodity Group Code",
    "Cargo Estimate Departure Date",
    "Cargo Departure Date",
    "Cargo Arrival Date",
    "Cargo Departure Date Ngen",
    "Cargo Arrival Date Ngen",
    "Cargo IsCargo Plane Manual",
    "Cargo Departure Ngen",
    "Cargo Arrival Ngen",
    "Cargo Departure Timezone Ngen",
    "Cargo Arrival Timezone Ngen",
    "Cargo EstLength Dimension",
    "Cargo EstWidth Dimension",
    "Cargo EstHeight Dimension",
    "Cargo ActualLength Dimension",
    "Cargo ActualWidth Dimension",
    "Cargo ActualHeight Dimension",
    "Cargo Nog",
    "Berat Final",
  ],
  cm: [
    "stt_no", // STT No
    "cargo_no", // Cargo No
    "manifest_validation", // Manifest Validation
    "courier_id", // Courier ID
    "courier_type", // Courier Type
    "created_at", // Created At
    "origin", // Origin
    "dest", // Dest.
    "dropoff_created_at", // Dropoff Created At
    "dropoff_konsol_id", // Dropoff Konsol ID
    "dropoff_location", // Dropoff Location
    "dropoff_partner_code", // Dropoff Partner Code
    "dropoff_partner_name", // Dropoff Partner Name
    "dropoff_partner_type", // Dropoff Partner Type
    "full_name", // Full Name
    "pickup_created_at", // Pickup Created At
    "pickup_konsol_id", // Pickup Konsol ID
    "pickup_location", // Pickup Location
    "pickup_parter_code", // Pickup Parter Code
    "pickup_partner_name", // Pickup Partner Name
    "pickup_partner_type", // Pickup Partner Type
    "status_validation", // Status Validation
    "vehicle_plate", // Vehicle Plate
    "vehicle_type", // Vehicle Type
    "sync_at", // Sync At
    "vendor_id", // Vendor ID
    "vendor_name", // Vendor Name
    "product", // Product (Mapping ke product_type)
  ],
  ms: [
    "Cargo No",
    "MAWB Pcs",
    "MAWB Weight",
    "STT No",
    "STT Pcs",
    "STT Gross Weight",
    "Origin",
    "Destination",
    "Product",
    "Flight/Truck/Train Date",
    "Flight/Truck/Train No",
    "ETD",
    "ETA",
    "Transit",
    "Created Date AWB",
    "Created Time AWB",
    "CONS number",
    "Type",
    "T",
  ],
};

export const LOCKED_MAP: Record<string, string[]> = {
  ic: ["STT No"],
  ls: ["STT No"],
  dt: ["STT No"],
  mt: ["Cargo No"],
  cm: ["cargo_no"],
  ms: ["Cargo No"],
};
